apiVersion: apps/v1
kind: Deployment
metadata:
  name: opsani-servo

spec:
  template:
    spec:
      containers:
        - name: main
          imagePullPolicy: Always
          image: opsani/servo-k8s-prom-vegeta
          args:
          - robert
          - '--auth-token=/etc/optune-auth/token'
          env:
          - name: OPTUNE_ACCOUNT
            value: kumul.us
