apiVersion: rbac.authorization.k8s.io/v1
kind: ServiceAccount
metadata:
  name: optune-servo

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: optune-servo
rules:
- apiGroups: ["extensions", "apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: optune-servo-rw-resources
subjects:
- kind: ServiceAccount
  name: optune-servo
roleRef:
  kind: Role
  name: optune-servo
  apiGroup: rbac.authorization.k8s.io
